(LOAD "Lab_2.rkt")

(LAST '())
(LAST 'A)
(LAST '(A . B))
(LAST '(A B C D))
(LAST '(() ()))
(LAST '((A . B) (C . D) (E . F)))
(LAST '(A B C D . F))
(LAST '(A S D F G H J K L Q W E R))
(LAST '(A (B C) D (F E) G (H I)))
(LAST '(A S D F G H J K L Q W E R . 2))
(LAST '(A S D F G H J K L Q W E (H)))
(LAST '(A S D F G H J K L Q W E (H)((U))))